// Exam version: new numbers for every version code, no hints or refreshers.
// GENERATED by tools/build-part2-exam.js from part2-site/. Edit files there, then rebuild.
window.PART2_CONFIG = { mode: 'exam', randomize: true, hints: false, title: 'ACC 211 Midterm: Part 2' };
